set_property IOSTANDARD LVCMOS33 [get_ports clk_pin]
set_property PACKAGE_PIN T18 [get_ports btn_pin]
set_property IOSTANDARD LVCMOS33 [get_ports btn_pin]
set_property IOSTANDARD LVCMOS33 [get_ports rxd_pin]
set_property DRIVE 12 [get_ports rxd_pin]
set_property SLEW SLOW [get_ports rxd_pin]
set_property PACKAGE_PIN Y9 [get_ports clk_pin]
set_property IOSTANDARD LVCMOS33 [get_ports rst_pin]
set_property DRIVE 12 [get_ports rst_pin]
set_property SLEW SLOW [get_ports rst_pin]
set_property PACKAGE_PIN Y10 [get_ports rxd_pin]
set_property PACKAGE_PIN P16 [get_ports rst_pin]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[7]}]
set_property DRIVE 12 [get_ports {led_pins[0]}]
set_property DRIVE 12 [get_ports {led_pins[1]}]
set_property DRIVE 12 [get_ports {led_pins[2]}]
set_property DRIVE 12 [get_ports {led_pins[3]}]
set_property DRIVE 12 [get_ports {led_pins[4]}]
set_property DRIVE 12 [get_ports {led_pins[5]}]
set_property DRIVE 12 [get_ports {led_pins[6]}]
set_property DRIVE 12 [get_ports {led_pins[7]}]
set_property SLEW SLOW [get_ports {led_pins[0]}]
set_property SLEW SLOW [get_ports {led_pins[1]}]
set_property SLEW SLOW [get_ports {led_pins[2]}]
set_property SLEW SLOW [get_ports {led_pins[3]}]
set_property SLEW SLOW [get_ports {led_pins[4]}]
set_property SLEW SLOW [get_ports {led_pins[5]}]
set_property SLEW SLOW [get_ports {led_pins[6]}]
set_property SLEW SLOW [get_ports {led_pins[7]}]


create_clock -period 10.000 -name clk_pin -waveform {0.000 5.000} [get_ports clk_pin]
set_input_delay -clock [get_clocks clk_pin] 0.000 [get_ports {rxd_pin rst_pin btn_pin}]
set_input_delay -clock [get_clocks clk_pin] -min -0.500 [get_ports {rxd_pin rst_pin btn_pin}]
set_output_delay -clock [get_clocks clk_pin] 0.000 [get_ports {led_pins[0] led_pins[1] led_pins[2] led_pins[3] led_pins[4] led_pins[5] led_pins[6] led_pins[7]}]

set_property IOB TRUE [get_ports {led_pins[0]}]
set_property IOB TRUE [get_ports {led_pins[1]}]
set_property IOB TRUE [get_ports {led_pins[2]}]
set_property IOB TRUE [get_ports {led_pins[3]}]
set_property IOB TRUE [get_ports {led_pins[4]}]
set_property IOB TRUE [get_ports {led_pins[5]}]
set_property IOB TRUE [get_ports {led_pins[6]}]
set_property IOB TRUE [get_ports {led_pins[7]}]
set_property LOC OLOGIC_X1Y0 [get_cells {led_ctl_i0/led_o_reg[0]}]
set_property LOC OLOGIC_X1Y43 [get_cells {led_ctl_i0/led_o_reg[2]}]
set_property LOC OLOGIC_X1Y44 [get_cells {led_ctl_i0/led_o_reg[3]}]
set_property LOC OLOGIC_X1Y45 [get_cells {led_ctl_i0/led_o_reg[5]}]
set_property LOC OLOGIC_X1Y46 [get_cells {led_ctl_i0/led_o_reg[7]}]
set_property LOC OLOGIC_X1Y47 [get_cells {led_ctl_i0/led_o_reg[4]}]
set_property LOC OLOGIC_X1Y48 [get_cells {led_ctl_i0/led_o_reg[6]}]
set_property LOC OLOGIC_X1Y49 [get_cells {led_ctl_i0/led_o_reg[1]}]
set_property PACKAGE_PIN U14 [get_ports {led_pins[0]}]
set_property PACKAGE_PIN U19 [get_ports {led_pins[1]}]
set_property PACKAGE_PIN W22 [get_ports {led_pins[2]}]
set_property PACKAGE_PIN V22 [get_ports {led_pins[3]}]
set_property PACKAGE_PIN U21 [get_ports {led_pins[4]}]
set_property PACKAGE_PIN U22 [get_ports {led_pins[5]}]
set_property PACKAGE_PIN T21 [get_ports {led_pins[6]}]
set_property PACKAGE_PIN T22 [get_ports {led_pins[7]}]
