# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_verilog {
  C:/Users/Xilinx/Desktop/xup_test/lab1/lab1.srcs/sources_1/imports/lab1/uart_rx_ctl.v
  C:/Users/Xilinx/Desktop/xup_test/lab1/lab1.srcs/sources_1/imports/lab1/uart_baud_gen.v
  C:/Users/Xilinx/Desktop/xup_test/lab1/lab1.srcs/sources_1/imports/lab1/meta_harden.v
  C:/Users/Xilinx/Desktop/xup_test/lab1/lab1.srcs/sources_1/imports/lab1/uart_rx.v
  C:/Users/Xilinx/Desktop/xup_test/lab1/lab1.srcs/sources_1/imports/lab1/led_ctl.v
  C:/Users/Xilinx/Desktop/xup_test/lab1/lab1.srcs/sources_1/imports/lab1/uart_led.v
}
read_xdc C:/Users/Xilinx/Desktop/xup_test/lab1/lab1.srcs/constrs_1/imports/lab1/uart_led_timing.xdc
set_property used_in_implementation false [get_files C:/Users/Xilinx/Desktop/xup_test/lab1/lab1.srcs/constrs_1/imports/lab1/uart_led_timing.xdc]

read_xdc C:/Users/Xilinx/Desktop/xup_test/lab1/lab1.srcs/constrs_1/imports/lab1/uart_led_pins.xdc
set_property used_in_implementation false [get_files C:/Users/Xilinx/Desktop/xup_test/lab1/lab1.srcs/constrs_1/imports/lab1/uart_led_pins.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Xilinx/Desktop/xup_test/lab1/lab1.data/wt [current_project]
set_property parent.project_dir C:/Users/Xilinx/Desktop/xup_test/lab1 [current_project]
synth_design -top uart_led -part xc7z020clg484-1
write_checkpoint uart_led.dcp
report_utilization -file uart_led_utilization_synth.rpt -pb uart_led_utilization_synth.pb
