# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths C:/Users/Xilinx/Desktop/xup_test/led_ip [current_fileset]

add_files C:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog C:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_xdc C:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/constrs_1/imports/lab4/lab4_system.xdc
set_property used_in_implementation false [get_files C:/Users/Xilinx/Desktop/xup_test/lab4/lab4.srcs/constrs_1/imports/lab4/lab4_system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Xilinx/Desktop/xup_test/lab4/lab4.data/wt [current_project]
set_property parent.project_dir C:/Users/Xilinx/Desktop/xup_test/lab4 [current_project]
synth_design -top design_1_wrapper -part xc7z020clg484-1
write_checkpoint design_1_wrapper.dcp
report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb
